# 📌 예외 처리
### 자바 메서드에서는 문제가 생기면 예외를 사용하여 자신을 호출한 메서드에 그 사실을 알려 준다.
- **예외 처리(exception handling)** : 실행 중에 생길 수 있는 '예외적인 상황'을 처리할 수 있는 깔끔하고도 부담이 없는 방법. 이 방법을 사용하면 오류 처리 코드를 한 군데로 모아둘 수 있기 때문에 코드를 이해하기도 매우 편리함

  메서드 선언에서 **`throws`** 구문을 찾으면 예외를 발생시킬 수 있다는 것을 알 수 있음

**실행 중에 오류가 발생할 수 있는 위험한 메서드의 경우에는 메서드 선언부에서 `throws SomeKindOfException` 같은 구문을 사용하여 예외를 선언해야 함.**

- **throws** : 예외를 발생시키는 것을 예외로 '던진다(throw)'라고 표현하기 때문에 `throws`라는 키워드를 사용함

### 컴파일러는 프로그래머가 위험한 메서드를 호출하고 있다는 것을 알아야 함.
```java
import javax.sound.midi.*;

public class MusicTest1 {
  public void play() {
    try {   // 위험한 부분은 try 블록에 넣는다. 여기에서 예외를 던질 수 있는건 getSequencer 메서드
      Sequencer sequencer = MidiSystem.getSequencer();
      System.out.println("Successfully got a sequencer");
    } catch (MidiUnavailableException e) {  // 예외적인 상황이 일어났을 때 할 일을 지정하기 위한 catch 블록을 만든다.
      System.out.println("Bummer");         // getSequencer()를 호출했을 때 MidiUnavailableException이 발생할 수 있다는 것을 의미
    }
  }

  public static void main(String[] args) {
    MusicTest1 mt = new MusicTest1();
    mt.play();
  }
}
```

### 예외도 객체이다.
예외는 `Exception`이라는 타입의 객체이다. `Exception` 타입의 객체에는 `Exception` 하위 클래스의 모든 인스턴스가 포함됨
```java
try {
  // 위험한 일을 한다.
} catch (Exception e) {
  // 문제를 처리한다.
}
```
위 코드의 **`catch`** 인자는 `Exception` 타입으로 선언되어 있고 매개변수는 `e`라는 이름을 가진 레퍼런스 변수이다.

- 예외를 던지는 위험한 코드
  ```java
  public void takeRisk() throws BadException { // BadExceptoin을 던질 수 있다는 것을 외부에 알림
    if (abandonAllHope) {
      throw new BadException();                // 새로운 Exception 객체를 만들고 던짐
    }
  }
  ```

- 그 위험한 메서드를 호출하는 코드
  ```java
  public void crossFingers() {
    try {
      anObject.takeRisk();
    } catch (BadException e) {
      System.out.println("Aaargh!");
      e.printStackTrace(); // 예외 상황을 해결할 수 없다면 printStackTrace() 메서드를 써서 스택 트레이스(stack trace) 정도는 해 줘야 함
    }
  }
  ```
  한 메서드에서 던진 것을 다른 메서드에서 잡아야 한다. 예외는 언제나 그 메서드를 호출한 곳으로 던져진다. 예외를 던지는 메서드에서는 반드시 그 메서드에서 예외를 던질 수 있다는 것을 선언해야 함


### try/catch 블록에서의 흐름 제어
- try 블록이 **성공**하면
  
  (`doRiskyThing()`에서 예외를 던지지 않으면)
  ```java
  try {
    Foo f = x.doRiskyThing();
    int b = f.getNum();
  } catch (Exception e) { 
    System.out.println("failed"); // catch 블록에 들어 있는 코드는 실행되지 않음
  }

  System.out.println("We made it!");
  
  // 출력 결과:
  // We made it!
  ```

- try 블록이 **실패**하면
  
  (`doRiskyThing()`에서 예외를 던지면)
  ```java
  try {
    Foo f = x.doRiskyThing();
    int b = f.getNum();     // try 블록의 나머지 부분은 절대 실행되지 않음
  } catch (Exception e) {
    System.out.println("failed");
  }

  System.out.println("We made it!);
  // 출력 결과:
  // failed
  // We made it!
  ```


- **무조건 실행할 내용**을 지정하는 방법
  
  예외 발생 여부와 상관없이 무조건 실행할 코드는 **`finally`** 블록에 집어넣으면 됨
  ```java
  try {
    turnOvenOn();
    x.bake();
  } catch (BakingException e) {
    e.printStackTrace();
  } finally {
    turnOvenOff();
  }
  ```
  - `try` 블록이 **실패**하면, 바로 `catch` 블록으로 넘어감. `catch` 블록이 종료되면 `finally` 블록이 실행. `finally` 블록이 종료되면 나머지 부분 실행
  - `try` 블록이 **성공**하면, `catch` 블록은 건너뛰고 `finally` 블록으로 넘어감. `finally` 블록이 종료되면 그 메서드의 나머지 부분이 실행
  - `try` 또는 `catch` 블록에 `return` 명령문이 있어도 `finally` 블록은 실행됨
  
